version: "3.1"

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres
    container_name: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend_network

  bff:
    container_name: bff
    image: bff
    command: 
      - "/app/wait-for-it.sh"
      - "db:5432"
      - "chunk_storage_1:8000"
      - "chunk_storage_2:8000"
      - "chunk_storage_3:8000"
      - "chunk_storage_4:8000"
      - "chunk_storage_5:8000"
      - "chunk_storage_6:8000"
      - "--"
      - "/app/myapp"
    ports:
      - "8000:8000"
    depends_on:
      - db
      - chunk_storage_1
      - chunk_storage_2
      - chunk_storage_3
      - chunk_storage_4
      - chunk_storage_5
      - chunk_storage_6
    networks:
      - backend_network
    environment:
      - STORAGES=6

  chunk_storage_1:
    container_name: chunk_storage_1
    volumes:
      - ./data/data1:/data
    image: chunk_storage
    networks:
      - backend_network

  chunk_storage_2:
    container_name: chunk_storage_2
    volumes:
      - ./data/data2:/data
    image: chunk_storage
    networks:
      - backend_network

  chunk_storage_3:
    container_name: chunk_storage_3
    volumes:
      - ./data/data3:/data
    image: chunk_storage
    networks:
      - backend_network

  chunk_storage_4:
    container_name: chunk_storage_4
    volumes:
      - ./data/data4:/data
    image: chunk_storage
    networks:
      - backend_network

  chunk_storage_5:
    container_name: chunk_storage_5
    volumes:
      - ./data/data5:/data
    image: chunk_storage
    networks:
      - backend_network

  chunk_storage_6:
    container_name: chunk_storage_6
    volumes:
      - ./data/data6:/data
    image: chunk_storage
    networks:
      - backend_network

